### ISSUE TITLE
I have other problem: Lighthouse and query

### ISSUE THREAD

**Issue by cfuhr** [nocio/headstart#4] opened 2019-11-15 16:25 UTC
Hello, when I want to make a query using Lighthouse I always receive an error.
If you can help me with this I would appreciate it.
I enclose screenshots.
![HeadStart_error](https://user-images.githubusercontent.com/14838455/68958674-5845e880-07ab-11ea-91cb-976134b995a5.png)
![HeadStart_Lighthouse_error](https://user-images.githubusercontent.com/14838455/68958682-5b40d900-07ab-11ea-94af-ec06c36f43cc.png)

**Comment by frthjf** [comment] 2019-11-15 20:36
Hi Claudio, 

For the first screenshot, from the error message it appears you are encountering this issue: https://github.com/nuwave/lighthouse/issues/730. The problem is that you just open the endpoint without sending a GraphQL query.

Now, I'm not sure what the second error message is because it's scrolled out of the view, but my suspicion is that there is a problem with the schema. If you've installed the blog.htm template, the problem might be that the Type `BackendUser` in the line
``` user: BackendUser @belongsTo``` is undefined. If so, just remove that line or add the type by installing the user template, but in general the error message in the HTML output will tell you what's wrong. 

Since it's a bit hard to workout the HTML error message from the HTML source, I recommend using https://insomnia.rest/ or some other client that renders it directly.

Hope that helps.

**Comment by cfuhr** [comment] 2019-11-20 15:13
Hello,

For the first screenshot it contains the browser view of the html code of the problem of the second screenshot.

**Comment by frthjf** [comment] 2019-11-20 20:39
Hi,

I'm sorry you are still encountering this issue. From the linked issue, the cause is most likely that the query is not being sent correctly. This could be a bug or something to do with the setup of the endpoint. Does the query also fail if you use a different query client like insomnia? 

Also, can you try and run the following query:
```
{
 headstart
}
```
Many thanks!

**Comment by cfuhr** [comment] 2019-11-20 22:14
Hi, I asked the question you asked for.
I used another graphql client, a firefox add-on.

![headstart_graphql](https://user-images.githubusercontent.com/14838455/69282696-a0a94000-0bc9-11ea-893b-b94a9bfdc031.png)

I attach the result in json format.

[headstart_graphql_json.txt](https://github.com/nocio/headstart/files/3871729/headstart_graphql_json.txt)

Regards

--
Claudio

**Comment by frthjf** [comment] 2019-11-20 22:21
Thanks, that seems to work correctly. What's the response for the blogPost query?

**Comment by cfuhr** [comment] 2019-11-21 00:10
![headstart_graphql_2](https://user-images.githubusercontent.com/14838455/69289070-2339fb80-0bda-11ea-93e4-0ceb28863226.png)

[headstart_graphql_blogPosts_error.txt](https://github.com/nocio/headstart/files/3872140/headstart_graphql_blogPosts_error.txt)

**Comment by frthjf** [comment] 2019-11-21 07:34
Thanks, this is the problem that I've mentioned above. 

In the schema, can you comment out line 18 like [here](https://github.com/nocio/headstart/blob/master/templates/rainlab_blog.htm) with a ``#``.

Or you can install the user template.

**Comment by frthjf** [comment] 2019-11-28 20:35
Hi @cfuhr, I'm closing this assuming it's not an issue any longer. Let me know if the issue still persists.

**Closed as completed by frthjf** 2019-11-28 20:35 UTC

**Comment by frthjf** [comment] 2020-07-15 20:38
Hi @cfuhr, I believe the error might have been caused by #9.
